version="2.0"
watch_list=["docs/src/*.md"]
ignore_list=["**/.*.md"]
style="basic"
hooks=["shebang", "quarto_attributes", "brei"]

# Get rid of warnings about unknown language
[[languages]]
name="JuliaREPL"
identifiers=["julia-repl"]
comment={open="#"}

[[languages]]
name="Mermaid"
identifiers=["mermaid"]
comment={open="#"}
